### ISSUE TITLE
Field DC Power

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#100]
**Issue:**
The powerplant add_dc_field asks for both the number_of_series_strings_wired_in_parallel and field_dc_power.  Normally, when using the Plant Predict UI, the field_dc_power is specified and the number_of_series_strings_wired_in_parallel is calculated in the backend. 

**Impact:**
Requiring both number_of_series_strings_wired_in_parallel and field_dc_power means the user needs to calculate one off of the other manually, prior to building the plant.  Also, because the two parameters are related, what happens when they are contradictory? 

**Solution:**
number_of_series_strings_wired_in_parallel = (field_dc_power x 1000)/(module_bin_class x modules_wired_in_series)

Not sure how we can extract the module_bin_class from the identified PAN file.

![image](https://user-images.githubusercontent.com/53441041/63037617-42571d80-be74-11e9-9514-358fd75c5d61.png)

**Comment by stephenkaplan** [comment]
@leighannngo something that might help me: what information do you have when building a plant? Is it usually the DC capacity of the field? And then do you also have dimension info (tables, rows, etc)? Since a lot of these variables are intertwined, it's hard to know what to have as inputs and what to have automatically set?

also, getting the bin class isn't an issue.

**Comment by stephenkaplan** [comment]
@leighannngo you can mostly disregard the previous comment. in general, tell me if this use case would work (this is sort of how the UI works, by the way). I think if we can sort this out, it will fix all of the issues pertaining to add_dc_field:

REQUIRED INPUTS TO ADD_DC_FIELD (just the ones pertaining to these issues, this isn't a complete list)
- field dc power OR number of strings in parallel (and an error will be thrown if the user specifies both to avoid conflict), where the one not specified will be calculated
- module id
- modules in series
- modules high
- row spacing OR GCR (and an error will be thrown if the user specifies both to avoid conflict), where the one not specified will be calculated


OPTIONAL INPUTS TO ADD_DC_FIELD
- modules wide (defaults to modules in series)

AUTOMATICALLY CALCULATED VALUES IN ADD_DC_FIELD
- number of rows
- dc field length
- dc field width
- number of tables
- module count

**Comment by stephenkaplan** [comment]
@leighannngo also, a bit conflicted on if i should make ground coverage ratio an input at all, or just have a separate helper for "calculate row spacing from gcr". seems like based on your other issue you might prefer that

**Comment by leighannngo** [comment]
@stephenkaplan the above use case is good, except I'd have number of rows be a required input, not an automatically calculated one.
I also think having the separate helper for calculating row spacing from GCR is better than having GCR as an input.

**Comment by stephenkaplan** [comment]
closed with https://github.com/stephenkaplan/plantpredict-python/commit/3dc7d8b13a5333dfbd6780f819565a6503336a4c
