### ISSUE TITLE
add_block does not contain the 'repeater' parameter

### ISSUE THREAD

**Issue by neelpatel2810** [stephenkaplan/plantpredict-python#166]
_calculate_num_inverters tries to access the 'repeater' element in the 'block' dictionary:
num_inverters.append(inverter['repeater'] * array['repeater'] * block['repeater'])

**Comment by stephenkaplan** [comment]
@neelpatel2810 thank you very much for reporting this. can you provide some sample code and also the error trace that occurs?

**Comment by neelpatel2810** [comment]
I am getting this 'KeyError' while running create_project_and_prediction_from_scratch.py script.
I also discovered a new bug (typo?) in the same example script where 'setpoint_kw' is the input parameter for the instances of calculate_field_dc_power_from_dc_ac_ratio function. It should be 'inverter_setpoint' instead.
