### ISSUE TITLE
Environmental Conditions>Plant Design Temperature

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#77]
**Issue:**
Generating a new prediction or cloning an existing one within a project does not carry over the ASHRAE temperatures (image 1)

**Impacts:**
This impacts the inverter kVA, causing it to be 0 (image 2).

This impacts the MV transformer (at array level, image 3).  If you enable the MV transformer and enable the "match total inverta kVA", the energy output will be 0.

**Solution:**
Have the ASHRAE temperatures correctly carry over to the prediction.

![image](https://user-images.githubusercontent.com/53441041/62386386-8bba7b00-b50c-11e9-85c4-f5488f0d3ca3.png)

![image](https://user-images.githubusercontent.com/53441041/62391458-bb23b480-b519-11e9-9a9f-b89a2418f9d3.png)

![image](https://user-images.githubusercontent.com/53441041/62391512-e1e1eb00-b519-11e9-91b5-46f09e049fcf.png)

**Comment by stephenkaplan** [comment]
potential to-do's

- add an ASHRAE class (might not be necessary for this specific use case)
- implement ASHRAE endpoints (might not be necessary for this specific use case), and test
- **make sure that ASHARE info gets transferred over in clone prediction**
- include ASHRAE in "creating project and prediction from scratch" example
- include ASHARE in "clone prediction" example if necessary

**Comment by stephenkaplan** [comment]
**update**: did end up adding an ASHRAE class with endpoint methods

**Comment by stephenkaplan** [comment]
@leighannngo the new default behavior for creating a prediction from scratch is that it will use the nearest ASHRAE station and fill in the plant design temperatures. the new default behavior for cloning a prediction is that it will carry over all of the information from the prediction being cloned. there is a way to override this behavior if you need

**Comment by leighannngo** [comment]
@stephenkaplan Awesome!  I don't think I'll need to override this yet, but it's good to know that the option is there!

**Comment by stephenkaplan** [comment]
**update for to-do's**

- ~~add an ASHRAE class (might not be necessary for this specific use case)~~ done.
- implement ASHRAE endpoints (might not be necessary for this specific use case), and test
- ~~make sure that ASHARE info gets transferred over in clone prediction~~ it does
include ASHRAE in "creating project and prediction from scratch" example
- ~~include ASHARE in "clone prediction" example if necessary~~ not necessary, plant design temperatures carry over in cloned prediction
