### ISSUE TITLE
Additional Night Loss

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#79]
**Issue:**
Some inverter models require us to input additional night losses.

**Impact:**
The user will have to input the additional night losses through the UI

**Solution:**
Have "additional night losses" as an input parameter in the SDK, default to 0.

![image](https://user-images.githubusercontent.com/53441041/62476822-98351280-b75c-11e9-907c-238ce1bb5882.png)

**Comment by stephenkaplan** [comment]
@leighannngo night time losses will be added as the input variable `additional_losses` to `add_array()`
