### ISSUE TITLE
Modules Wide

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#80]
**Issue:**
Modules wide is calculated in the SDK by dividing the product of the "number of series strings wired in parallel" and "modules wired in series" by the "number of rows".

**Impact:**
If any combination of the number of series strings wired in parallel, modules wired in series, and the number of rows that causes the number of modules wide to be a non-integer value or greater than 100, the the plant builder errors out.

**Solution:**
Have the user specify the number of modules wide and the number of rows.  Allow plant predict to calculate the tables per row.  Default modules wide to modules in series and number of rows to 1.

![image](https://user-images.githubusercontent.com/53441041/62478594-51491c00-b760-11e9-863a-8029414cb4af.png)

**Comment by stephenkaplan** [comment]
- update any documentation as well as example usage

**Comment by stephenkaplan** [comment]
current calculation referenced in "Issue" above:

```python

int(number_of_series_strings_wired_in_parallel*modules_wired_in_series/float(number_of_rows))

```

**Comment by stephenkaplan** [comment]
@leighannngo question: you mention to default number of rows to 1....but wouldn't that create a conflict with your suggestion of defaulting modules_wide to modules_wired_in_series? I might be misunderstanding

**Comment by leighannngo** [comment]
@stephenkaplan The real issue is having modules_wide calculated when it'd be better to make it user specified.  If number_of_rows is 1, all that would happen is you would have a single row-array with a lot of tables--but, let's make it so that the number of rows must be specified else we're given an error.
