### ISSUE TITLE
Power Plant System

### ISSUE THREAD

**Issue by leighannngo** [stephenkaplan/plantpredict-python#82]
**Issue:**
The SDK doesn't have an option to specify a Power Plant output limit, HV transformers, or transmission lines.

**Impact:**
User needs to go into the UI to specify these.  (This is not high priority as this work-around isn't difficult or time consuming).

**Solution:**
Add the output limit, HV transformers, and transmission lines as an input parameter.  Default to none for all.

![image](https://user-images.githubusercontent.com/53441041/62483162-e4d41a00-b76b-11e9-9ffd-386c034d93fe.png)

**Comment by stephenkaplan** [comment]
@leighannngo there's more or less already a way to do this, I'll probably create an Example Usage for "setting system-level power plant parameters). likely will also add methods for `add_tranformer` and `add_transmission_line` to go along with the other "power plant builder" methods

**Comment by stephenkaplan** [comment]
@leighannngo confirmed that I did what I described in the above comment
